In [5]:
import pandas as pd
import matplotlib.pyplot as plt
import pickle
from pandas_profiling import ProfileReport
import numpy as np

In [9]:
data = pd.read_csv("player.csv")

In [10]:
data

Unnamed: 0             Unnamed: 0_level_0 Regular Season Regular Season.1  \
0          NaN                           Team              W                L   
1          0.0                     LDLC ASVEL             26                8   
2          1.0               AS Monaco Basket             25                9   
3          2.0               Metropolitans 92             24               10   
4          3.0                      JDA Dijon             20               14   
5          4.0                    Limoges CSP             20               14   
6          5.0                 SIG Strasbourg             19               15   
7          6.0  Élan Béarnais Pau-Lacq-Orthez             19               15   
8          7.0                  Cholet Basket             18               16   
9          8.0                    Nanterre 92             17               17   
10         9.0          Le Mans Sarthe Basket             17               17   
11        10.0                       JL Bourg             15               19   
12        11.0       BCM Gravelines-Dunkerque             13               21   
13        12.0          Chorale Roanne Basket             13               21   
14        13.0                 ESSM Le Portel             13               21   
15        14.0               Paris Basketball             13               21   
16        15.0          Orléans Loiret Basket             12               22   
17        16.0                   Fos Provence             12               22   
18        17.0               Champagne Basket             10               24   

   Regular Season.2  
0              W/L%  
1             0.765  
2             0.735  
3             0.706  
4             0.588  
5             0.588  
6             0.559  
7             0.559  
8             0.529  
9               0.5  
10              0.5  
11            0.441  
12            0.382  
13            0.382  
14            0.382  
15            0.382  
16            0.353  
17            0.353  
18            0.294

In [11]:
data.head()

Unnamed: 0 Unnamed: 0_level_0 Regular Season Regular Season.1  \
0         NaN               Team              W                L   
1         0.0         LDLC ASVEL             26                8   
2         1.0   AS Monaco Basket             25                9   
3         2.0   Metropolitans 92             24               10   
4         3.0          JDA Dijon             20               14   

  Regular Season.2  
0             W/L%  
1            0.765  
2            0.735  
3            0.706  
4            0.588

In [12]:
data.tail()

Unnamed: 0     Unnamed: 0_level_0 Regular Season Regular Season.1  \
14        13.0         ESSM Le Portel             13               21   
15        14.0       Paris Basketball             13               21   
16        15.0  Orléans Loiret Basket             12               22   
17        16.0           Fos Provence             12               22   
18        17.0       Champagne Basket             10               24   

   Regular Season.2  
14            0.382  
15            0.382  
16            0.353  
17            0.353  
18            0.294

In [13]:
data.describe()

Unnamed: 0
count   18.000000
mean     8.500000
std      5.338539
min      0.000000
25%      4.250000
50%      8.500000
75%     12.750000
max     17.000000

In [15]:
pr = ProfileReport(data)

In [16]:
pr.to_widgets()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render widgets:   0%|          | 0/1 [00:00<?, ?it/s]

In [17]:
pr.to_file('ProfileReport.html')

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [33]:
data = data.tail(15)

In [34]:
data

Unnamed: 0     Unnamed: 0_level_0 Regular Season Regular Season.1  \
14        13.0         ESSM Le Portel             13               21   
15        14.0       Paris Basketball             13               21   
16        15.0  Orléans Loiret Basket             12               22   
17        16.0           Fos Provence             12               22   
18        17.0       Champagne Basket             10               24   

   Regular Season.2  
14            0.382  
15            0.382  
16            0.353  
17            0.353  
18            0.294

In [41]:
x = data[['Regular Season']]

In [42]:
y = data['Regular Season.1']

In [43]:
!pip install sklearn

In [44]:
from sklearn.linear_model import LinearRegression

In [45]:
linear = LinearRegression()

In [46]:
linear.fit(x,y)

LinearRegression()

In [47]:
linear.intercept_

34.00000000000001

In [48]:
linear.coef_

array([-1.])

In [49]:
file = 'linear_reg.sav'
pickle.dump(linear, open(file, 'wb'))

In [50]:
linear.predict([[45]])

array([-11.])

In [53]:
l = [40,15,6,17,8]

In [54]:
for i in l:
    print(linear.predict([[i]]))

[-6.]
[19.]
[28.]
[17.]
[26.]


In [55]:
saved_model = pickle.load(open(file,'rb'))

In [56]:
saved_model.predict([[20]])

array([14.])

In [57]:
linear.score(x,y)

1.0

In [ ]:
https://archive.ics.uci.edu/ml/datasets/AI4I+2020+Predictive+Maintenance+Dataset

In [ ]:
load data--profiling data--write your analysisof data--NAN, imputation--Not normal--handle it--check multicollinearity--build  model--saveit--model accuracy--10 test case