In [3]:
import numpy as np

In [4]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [5]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [6]:
np.array([1,2,3,4,5, "kesh", 4+8j])#upcast to string

array(['1', '2', '3', '4', '5', 'kesh', '(4+8j)'], dtype='<U64')

In [7]:
np.array([1,2,3,4,5, 6.0])#upcast to float

array([1., 2., 3., 4., 5., 6.])

In [8]:
np.array([[1,3], [3,4], [6,7]])

array([[1, 3],
       [3, 4],
       [6, 7]])

In [9]:
np.array([[1,3], [3,4], [6,7,8]])

C:\Users\kesdan02\AppData\Local\Temp/ipykernel_24112/1024472721.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1,3], [3,4], [6,7,8]])


array([list([1, 3]), list([3, 4]), list([6, 7, 8])], dtype=object)

In [10]:
np.array([[[1,3], [3,4]], [[6,7], [8,9]]])

array([[[1, 3],
        [3, 4]],

       [[6, 7],
        [8, 9]]])

In [11]:
np.array([1,2,3], ndmin=3)

array([[[1, 2, 3]]])

In [12]:
np.array([1,2,3], ndmin=30)

array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1, 2, 3]]]]]]]]]]]]]]]]]]]]]]]]]]]]]])

In [13]:
np.array([1,2,3], dtype = complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [14]:
np.array([(1,2), (3,4)])

array([[1, 2],
       [3, 4]])

In [15]:
np.array([[1,2], [3,4]])

array([[1, 2],
       [3, 4]])

In [16]:
np.array([(1,2,3,4)])

array([[1, 2, 3, 4]])

In [17]:
np.array([[1,2], [3,4]], dtype = [('a','i2'), ('b', '<i8')])

array([[(1, 1), (2, 2)],
       [(3, 3), (4, 4)]], dtype=[('a', '<i2'), ('b', '<i8')])

In [18]:
arr = np.array([(1,2), (3,4)], dtype = [('a','i2'), ('b', '<i8')])

In [19]:
arr[0]

(1, 2)

In [20]:
arr[0][0]

1

In [21]:
type(arr[0][0])

numpy.int16

In [22]:
arr[0][1]

2

In [23]:
type(arr[0][1])

numpy.int64

In [24]:
arr1 = np.array([[1,2], [3,4]])

In [25]:
arr1

array([[1, 2],
       [3, 4]])

In [26]:
arr[0][1]

2

In [27]:
type(arr[0][1])

numpy.int64

In [28]:
np.mat(arr)

matrix([[(1, 2), (3, 4)]], dtype=[('a', '<i2'), ('b', '<i8')])

In [29]:
np.matrix(arr)

matrix([[(1, 2), (3, 4)]], dtype=[('a', '<i2'), ('b', '<i8')])

In [30]:
l = [3,4,5,6,7,]

In [31]:
np.array(l)

array([3, 4, 5, 6, 7])

In [32]:
np.asarray(l)

array([3, 4, 5, 6, 7])

In [33]:
np.asanyarray(l)

array([3, 4, 5, 6, 7])

In [34]:
mat =np.mat(arr)

In [35]:
np.asanyarray(mat)#matrix is a kind of array so conversion didn't happen

matrix([[(1, 2), (3, 4)]], dtype=[('a', '<i2'), ('b', '<i8')])

In [36]:
np.asarray(mat)

array([[(1, 2), (3, 4)]], dtype=[('a', '<i2'), ('b', '<i8')])

In [37]:
issubclass(np.matrix, np.ndarray)

True

In [38]:
issubclass(np.ndarray, np.matrix)

False

In [39]:
arr

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [40]:
a = arr #shallow copy

In [41]:
b = np.copy(arr) #deep copy

In [42]:
arr[0][0] = 67 #array data are mutable

In [43]:
arr

array([(67, 2), ( 3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [44]:
a

array([(67, 2), ( 3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [45]:
b

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [46]:
arr[0:10]

array([(67, 2), ( 3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [47]:
arr[-1]

(3, 4)

In [48]:
for i in arr:
    print(i)

(67, 2)
(3, 4)


In [49]:
np.fromfunction(lambda i, j: i==j,(4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [50]:
type(np.fromfunction(lambda i, j: i==j,(4,4))) #generate nd darray

numpy.ndarray

In [51]:
np.fromfunction(lambda i, j: i*j,(4,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [52]:
np.fromfunction(lambda i, j: i**j,(4,4))

array([[ 1.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  2.,  4.,  8.],
       [ 1.,  3.,  9., 27.]])

In [53]:
np.fromfunction(lambda i, j: i/j,(4,4)) #inf keyword exists in numpy

C:\Users\kesdan02\AppData\Local\Temp/ipykernel_24112/292923348.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.fromfunction(lambda i, j: i/j,(4,4)) #inf keyword exists in numpy
C:\Users\kesdan02\AppData\Local\Temp/ipykernel_24112/292923348.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.fromfunction(lambda i, j: i/j,(4,4)) #inf keyword exists in numpy


array([[       nan, 0.        , 0.        , 0.        ],
       [       inf, 1.        , 0.5       , 0.33333333],
       [       inf, 2.        , 1.        , 0.66666667],
       [       inf, 3.        , 1.5       , 1.        ]])

In [54]:
1/0

ZeroDivisionError: division by zero

In [ ]:
(i*i for i in range(5))

In [55]:
[(i*i for i in range(5))]

[<generator object <genexpr> at 0x0000025CD2D4E7B0>]

In [56]:
def test(x):
    yield x

In [57]:
test(5)

<generator object test at 0x0000025CD2D4EAC0>

In [58]:
 gen = (i*i for i in range(5))

In [59]:
np.fromiter(gen, dtype= int)

array([ 0,  1,  4,  9, 16])

In [60]:
np.fromiter(range(5), dtype= int) #generate nd array from a generator

array([0, 1, 2, 3, 4])

In [61]:
np.fromstring('1,3,4,5', sep = ',', dtype = int)

array([1, 3, 4, 5])

In [62]:
np.fromstring('1,3,4,5', sep = ',', dtype = complex)

array([1.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

In [63]:
l =[3,4,5,6,7,8]

In [64]:
np.array(l)

array([3, 4, 5, 6, 7, 8])

In [65]:
arr2 = np.array(l)

In [66]:
arr3 = np.array([[1,2,3,4],[2,3,4,5], [4,5,6,7]])

In [68]:
type(arr3)

numpy.ndarray

In [69]:
arr3

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [4, 5, 6, 7]])

In [70]:
aar3.ndim

NameError: name 'aar3' is not defined

In [71]:
arr3.size

12

In [72]:
arr3.shape

(3, 4)

In [73]:
arr3.dtype

dtype('int32')

In [74]:
arr2.size

6

In [78]:
arr2.ndim

1

In [79]:
arr2.shape

(6,)

In [84]:
arr4 = np.array([[[1,2,3,4], [4,5,6,7]], [[1,2,3,4], [4,5,6,7]]])

In [85]:
arr4

array([[[1, 2, 3, 4],
        [4, 5, 6, 7]],

       [[1, 2, 3, 4],
        [4, 5, 6, 7]]])

In [86]:
arr4.size

16

In [87]:
arr4.ndim

3

In [88]:
arr4.shape

(2, 2, 4)

In [98]:
arr5 = np.array([[[[1,2,3,4], [4,5,6,7]], [[1,2,3,4], [4,5,6,7]]]])

In [99]:
arr5

array([[[[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]]]])

In [100]:
arr5.ndim

4

In [101]:
arr5.shape

(1, 2, 2, 4)

In [102]:
arr6 =np.array([[[[1,2,3,4], [4,5,6,7], [1,2,3,4], [4,5,6,7]]]])

In [103]:
arr6.ndim

4

In [104]:
arr6.shape

(1, 1, 4, 4)

In [105]:
range(5)

range(0, 5)

In [106]:
list(range(5))

[0, 1, 2, 3, 4]

In [107]:
list(range(5.5))

TypeError: 'float' object cannot be interpreted as an integer

In [110]:
np.arange(5.5)

array([0., 1., 2., 3., 4., 5.])

In [116]:
np.arange(5.5, 9, 0.3)

array([5.5, 5.8, 6.1, 6.4, 6.7, 7. , 7.3, 7.6, 7.9, 8.2, 8.5, 8.8])

In [117]:
np.arange(5.5, 8, -0.3)

array([], dtype=float64)

In [115]:
np.arange(9, 5.5, -0.3)

array([9. , 8.7, 8.4, 8.1, 7.8, 7.5, 7.2, 6.9, 6.6, 6.3, 6. , 5.7])

In [118]:
np.arange(5, 9, 1)

array([5, 6, 7, 8])

In [120]:
np.linspace(3,8)

array([3.        , 3.10204082, 3.20408163, 3.30612245, 3.40816327,
       3.51020408, 3.6122449 , 3.71428571, 3.81632653, 3.91836735,
       4.02040816, 4.12244898, 4.2244898 , 4.32653061, 4.42857143,
       4.53061224, 4.63265306, 4.73469388, 4.83673469, 4.93877551,
       5.04081633, 5.14285714, 5.24489796, 5.34693878, 5.44897959,
       5.55102041, 5.65306122, 5.75510204, 5.85714286, 5.95918367,
       6.06122449, 6.16326531, 6.26530612, 6.36734694, 6.46938776,
       6.57142857, 6.67346939, 6.7755102 , 6.87755102, 6.97959184,
       7.08163265, 7.18367347, 7.28571429, 7.3877551 , 7.48979592,
       7.59183673, 7.69387755, 7.79591837, 7.89795918, 8.        ])

In [121]:
np.linspace(1,2)#by default no. is 50

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [122]:
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [124]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [127]:
np.zeros((2,5, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [128]:
np.ones((2,5, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [130]:
np.ones((2,5, 4))+5

array([[[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]],

       [[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]]])

In [131]:
np.empty((3,4))

array([[5.5, 5.8, 6.1, 6.4],
       [6.7, 7. , 7.3, 7.6],
       [7.9, 8.2, 8.5, 8.8]])

In [132]:
np.empty(5)

array([7.74860419e-304, 7.74860419e-304, 7.74860419e-304, 7.74860419e-304,
       7.74860419e-304])

In [133]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [134]:
np.linspace(2,4,4)

array([2.        , 2.66666667, 3.33333333, 4.        ])

In [135]:
np.linspace(2,4,4, endpoint=False)

array([2. , 2.5, 3. , 3.5])

In [136]:
np.linspace(2,4,4, endpoint=False, axis=0)

array([2. , 2.5, 3. , 3.5])

In [137]:
np.linspace([2,4],4, endpoint=False, axis=1)

array([[2.  , 2.04, 2.08, 2.12, 2.16, 2.2 , 2.24, 2.28, 2.32, 2.36, 2.4 ,
        2.44, 2.48, 2.52, 2.56, 2.6 , 2.64, 2.68, 2.72, 2.76, 2.8 , 2.84,
        2.88, 2.92, 2.96, 3.  , 3.04, 3.08, 3.12, 3.16, 3.2 , 3.24, 3.28,
        3.32, 3.36, 3.4 , 3.44, 3.48, 3.52, 3.56, 3.6 , 3.64, 3.68, 3.72,
        3.76, 3.8 , 3.84, 3.88, 3.92, 3.96],
       [4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  ,
        4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  ,
        4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  ,
        4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  ,
        4.  , 4.  , 4.  , 4.  , 4.  , 4.  ]])

In [138]:
np.logspace(2,3,5)

array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519,
       1000.        ])

In [140]:
np.linspace([2],[3], 10)

array([[2.        ],
       [2.11111111],
       [2.22222222],
       [2.33333333],
       [2.44444444],
       [2.55555556],
       [2.66666667],
       [2.77777778],
       [2.88888889],
       [3.        ]])

In [141]:
np.linspace([2],[3], 10, axis=1)

array([[2.        , 2.11111111, 2.22222222, 2.33333333, 2.44444444,
        2.55555556, 2.66666667, 2.77777778, 2.88888889, 3.        ]])

In [142]:
d = np.linspace(4,7,40)

In [143]:
d

array([4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
       4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
       4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
       5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846,
       5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
       5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
       6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
       6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ])

In [144]:
d.ndim

1

In [145]:
d.shape

(40,)

In [147]:
d.reshape(40,1)#Transpose

array([[4.        ],
       [4.07692308],
       [4.15384615],
       [4.23076923],
       [4.30769231],
       [4.38461538],
       [4.46153846],
       [4.53846154],
       [4.61538462],
       [4.69230769],
       [4.76923077],
       [4.84615385],
       [4.92307692],
       [5.        ],
       [5.07692308],
       [5.15384615],
       [5.23076923],
       [5.30769231],
       [5.38461538],
       [5.46153846],
       [5.53846154],
       [5.61538462],
       [5.69230769],
       [5.76923077],
       [5.84615385],
       [5.92307692],
       [6.        ],
       [6.07692308],
       [6.15384615],
       [6.23076923],
       [6.30769231],
       [6.38461538],
       [6.46153846],
       [6.53846154],
       [6.61538462],
       [6.69230769],
       [6.76923077],
       [6.84615385],
       [6.92307692],
       [7.        ]])

In [148]:
d.reshape(1,2,20)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
         4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846],
        [5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
         6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [149]:
d.reshape(2,1,20)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
         4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846]],

       [[5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
         6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [150]:
d.reshape(1,2,1,20)

array([[[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
          4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
          4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
          5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846]],

        [[5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
          5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
          6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
          6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]]])

In [151]:
d.reshape(3,1,20)

ValueError: cannot reshape array of size 40 into shape (3,1,20)

In [152]:
np.random.rand(3)

array([0.8556008 , 0.93348576, 0.12944506])

In [153]:
np.random.rand(3)

array([0.09697257, 0.63011954, 0.69136733])

In [154]:
np.random.randn(3)

array([ 0.23452696, -1.39794835,  0.16702236])

In [155]:
np.random.rand(3,4)

array([[0.94022489, 0.23540865, 0.08524999, 0.81043964],
       [0.08953039, 0.03806713, 0.8679809 , 0.11893585],
       [0.46339861, 0.52463615, 0.46366603, 0.88636087]])

In [156]:
np.random.rand(2,3,4)

array([[[0.47207789, 0.65145291, 0.34224851, 0.62946845],
        [0.99267527, 0.06234361, 0.562912  , 0.67355238],
        [0.32071408, 0.5891483 , 0.30670184, 0.36869991]],

       [[0.0153298 , 0.65849367, 0.93009093, 0.42099705],
        [0.95305246, 0.1234506 , 0.66711752, 0.35603927],
        [0.64900358, 0.67709562, 0.61358544, 0.10859518]]])

In [164]:
np.random.randint(5,10, (4,4))

array([[7, 9, 5, 9],
       [6, 5, 5, 5],
       [7, 6, 6, 9],
       [7, 5, 7, 9]])

In [165]:
np.random.rand(2,3,4)

array([[[0.32270594, 0.77982556, 0.01853812, 0.62480593],
        [0.59088316, 0.5337102 , 0.54609515, 0.38687403],
        [0.40863379, 0.42453942, 0.35607701, 0.59372485]],

       [[0.11510613, 0.75149441, 0.33105194, 0.66822965],
        [0.7523229 , 0.98913798, 0.74418579, 0.61278652],
        [0.50355533, 0.3695632 , 0.99590915, 0.55713986]]])

In [168]:
arr = np.random.randint(2,8,(2,2))

In [169]:
arr

array([[5, 7],
       [4, 5]])

In [170]:
arr.reshape(1,4)

array([[5, 7, 4, 5]])

In [171]:
arr.reshape(2,1,2)

array([[[5, 7]],

       [[4, 5]]])

In [172]:
arr.reshape(4,-25465)

array([[5],
       [7],
       [4],
       [5]])

In [174]:
arr.max()

7

In [175]:
arr.min()

4

In [176]:
arr = np.random.randint(4,100,(5,5))

In [177]:
arr

array([[18, 95, 26, 19, 38],
       [18, 51,  6,  8, 36],
       [ 7, 53, 85, 19, 84],
       [51, 63, 26, 19, 74],
       [58, 27, 17, 40, 23]])

In [178]:
arr[3:,3:]

array([[19, 74],
       [40, 23]])

In [180]:
arr[0:, [1,3]]

array([[95, 19],
       [51,  8],
       [53, 19],
       [63, 19],
       [27, 40]])

In [181]:
arr>10

array([[ True,  True,  True,  True,  True],
       [ True,  True, False, False,  True],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [182]:
arr[arr>10]

array([18, 95, 26, 19, 38, 18, 51, 36, 53, 85, 19, 84, 51, 63, 26, 19, 74,
       58, 27, 17, 40, 23])

In [183]:
arr*arr

array([[ 324, 9025,  676,  361, 1444],
       [ 324, 2601,   36,   64, 1296],
       [  49, 2809, 7225,  361, 7056],
       [2601, 3969,  676,  361, 5476],
       [3364,  729,  289, 1600,  529]])

In [184]:
arr1 = np.random.randint(2,4,(3,3))

In [185]:
arr2 = np.random.randint(2,4,(3,3))

In [186]:
arr1

array([[2, 3, 3],
       [3, 3, 2],
       [2, 2, 3]])

In [187]:
arr2

array([[3, 2, 3],
       [3, 2, 3],
       [3, 2, 3]])

In [188]:
arr1*arr2

array([[6, 6, 9],
       [9, 6, 6],
       [6, 4, 9]])

In [189]:
arr1@arr2 #matrix multiplication

array([[24, 16, 24],
       [24, 16, 24],
       [21, 14, 21]])

In [190]:
arr/0

C:\Users\kesdan02\AppData\Local\Temp/ipykernel_24112/4291252909.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr/0


array([[inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf]])

In [191]:
arr**2

array([[ 324, 9025,  676,  361, 1444],
       [ 324, 2601,   36,   64, 1296],
       [  49, 2809, 7225,  361, 7056],
       [2601, 3969,  676,  361, 5476],
       [3364,  729,  289, 1600,  529]], dtype=int32)

In [193]:
arr = np.zeros((3,4))

In [194]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [195]:
a = np.array([1,2,3,4])

In [196]:
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [197]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [203]:
b = np.array([[5,6,7]])

In [204]:
b

array([[5, 6, 7]])

In [205]:
b.reshape(3,1)+arr

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [206]:
b

array([[5, 6, 7]])

In [207]:
b.T+arr

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [210]:
arr2 = np.random.rand(2,4)

In [212]:
np.sqrt(arr2)

array([[0.50184348, 0.2525476 , 0.36504454, 0.66615203],
       [0.97706989, 0.89938174, 0.5647592 , 0.6253544 ]])

In [213]:
np.exp(arr2)

array([[1.28639905, 1.0658582 , 1.14254418, 1.55855409],
       [2.59780166, 2.2454086 , 1.3756866 , 1.47855924]])

In [214]:
np.log10(arr2)

array([[-0.59886343, -1.19531349, -0.87530829, -0.35285329],
       [-0.02014874, -0.09211187, -0.49627337, -0.40774758]])

In [215]:
np.random.seed(13)

In [218]:
np.random.rand(2,4)

array([[0.25627995, 0.34758122, 0.00941277, 0.35833378],
       [0.94909418, 0.21789901, 0.31939137, 0.91777239]])

In [220]:
np.random.seed(13)
np.random.rand(2,4)

array([[0.77770241, 0.23754122, 0.82427853, 0.9657492 ],
       [0.97260111, 0.45344925, 0.60904246, 0.77552651]])